#!/usr/bin/env python3
"""Draws the artwork of the "Sakura Night" theme: background layers and tab icons.

Everything is original and generated by code (no third-party art). Output goes to
app/src/main/assets/themes/sakura-night/{images,icons}.

Usage: python3 tools/themes/make_sakura_night_art.py
Needs Pillow and numpy.
"""
import math
import os
import random

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter

W, H = 1920, 1080
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "app", "src", "main", "assets", "themes", "sakura-night")


def lerp(a, b, t):
    return a + (b - a) * t


def blur(img, radius):
    return img.filter(ImageFilter.GaussianBlur(radius))


def gradient(stops):
    """Vertical gradient image (RGB) from [(position 0..1, (r,g,b)), ...]."""
    ys = np.linspace(0, 1, H)
    cols = np.zeros((H, 3))
    for c in range(3):
        cols[:, c] = np.interp(ys, [s[0] for s in stops], [s[1][c] for s in stops])
    arr = np.repeat(cols[:, None, :], W, axis=1)
    return Image.fromarray(arr.astype("uint8"), "RGB")


def glow_disc(cx, cy, r, color, alpha, sigma):
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=color + (int(255 * alpha),))
    return blur(layer, sigma)


# --------------------------------------------------------------------------- sky
def make_sky():
    rnd = random.Random(7)
    img = gradient([
        (0.00, (7, 5, 24)), (0.30, (22, 12, 58)), (0.55, (58, 24, 88)),
        (0.78, (112, 38, 98)), (1.00, (196, 92, 148)),
    ]).convert("RGBA")

    # soft cloud streaks near the horizon
    clouds = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    cd = ImageDraw.Draw(clouds)
    for _ in range(14):
        x, y = rnd.randint(-200, W), rnd.randint(int(H * 0.45), int(H * 0.8))
        w, h = rnd.randint(300, 760), rnd.randint(14, 40)
        cd.ellipse([x, y, x + w, y + h], fill=(255, rnd.randint(130, 170), rnd.randint(190, 220), rnd.randint(22, 46)))
    img = Image.alpha_composite(img, blur(clouds, 26))

    # stars: many faint ones, a few with a small cross flare
    stars = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sd = ImageDraw.Draw(stars)
    for _ in range(520):
        x, y = rnd.randint(0, W), int((rnd.random() ** 1.6) * H * 0.7)
        b = int(90 + rnd.random() ** 2 * 165)
        r = rnd.choice([0.7, 0.9, 1.1, 1.4])
        sd.ellipse([x - r, y - r, x + r, y + r], fill=(255, 240, 250, b))
    for _ in range(26):
        x, y = rnd.randint(40, W - 40), int((rnd.random() ** 1.4) * H * 0.55)
        l = rnd.randint(6, 13)
        sd.line([x - l, y, x + l, y], fill=(255, 230, 245, 170), width=1)
        sd.line([x, y - l, x, y + l], fill=(255, 230, 245, 170), width=1)
    img = Image.alpha_composite(img, stars)
    img = Image.alpha_composite(img, blur(stars, 2.4))

    # moon with a wide pink halo
    mx, my, mr = 1500, 500, 112
    img = Image.alpha_composite(img, glow_disc(mx, my, mr * 2.4, (255, 150, 200), 0.30, 120))
    img = Image.alpha_composite(img, glow_disc(mx, my, mr * 1.35, (255, 215, 235), 0.45, 46))
    moon = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    md = ImageDraw.Draw(moon)
    for i in range(mr, 0, -2):  # subtle sphere shading
        t = i / mr
        md.ellipse([mx - i, my - i, mx + i, my + i], fill=(255, int(lerp(250, 232, t)), int(lerp(252, 240, t)), 255))
    for _ in range(6):  # faint seas
        cx, cy, r = mx + rnd.randint(-70, 70), my + rnd.randint(-70, 70), rnd.randint(10, 30)
        if math.hypot(cx - mx, cy - my) + r < mr - 6:
            md.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(238, 220, 234, 70))
    img = Image.alpha_composite(img, blur(moon, 0.8))
    return img.convert("RGB")


# --------------------------------------------------------------------------- mountains
def ridge_points(base, amp, seed, octaves=5):
    rnd = random.Random(seed)
    phases = [rnd.random() * 2 * math.pi for _ in range(octaves)]
    xs = np.arange(0, W + 1, 4)
    ys = np.zeros_like(xs, dtype=float)
    for k in range(octaves):
        f = 1.0 * (1.9 ** k)
        ys += (amp / (1.65 ** k)) * np.sin(2 * math.pi * f * xs / W + phases[k])
    return xs, base + ys


def fill_ridge(layer, xs, ys, color):
    d = ImageDraw.Draw(layer)
    pts = list(zip(xs.tolist(), ys.tolist())) + [(W, H), (0, H)]
    d.polygon(pts, fill=color)


def make_mountains():
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))

    # far range with a stylised Fuji (concave slopes, snow cap)
    far = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    xs, ys = ridge_points(base=H * 0.70, amp=34, seed=3)
    cx, w, h = 600, 520, 330
    for i, x in enumerate(xs):
        dx = abs(x - cx) / w
        if dx < 1:
            ys[i] = min(ys[i], H * 0.72 - h * (1 - dx) ** 1.45)
    fill_ridge(far, xs, ys, (86, 46, 120, 255))
    # snow cap: the top part of the cone, tinted by the moonlight
    snow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sd = ImageDraw.Draw(snow)
    rnd = random.Random(11)
    top = H * 0.72 - h
    for x in range(cx - 190, cx + 191, 3):
        dx = abs(x - cx) / w
        if dx < 1:
            edge = H * 0.72 - h * (1 - dx) ** 1.45
            drip = 52 + 38 * abs(math.sin(x * 0.045)) + rnd.random() * 14
            sd.line([x, edge, x, min(edge + drip * (1 - abs(x - cx) / 230), edge + 120)], fill=(255, 222, 238, 235), width=3)
    far = Image.alpha_composite(far, blur(snow, 1.2))
    img = Image.alpha_composite(img, far)
    img = Image.alpha_composite(img, mist(H * 0.70, (255, 170, 205), 30))

    mid = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    xs, ys = ridge_points(base=H * 0.78, amp=48, seed=5)
    fill_ridge(mid, xs, ys, (50, 26, 86, 255))
    img = Image.alpha_composite(img, mid)
    img = Image.alpha_composite(img, mist(H * 0.77, (255, 150, 195), 26))

    near = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    xs, ys = ridge_points(base=H * 0.87, amp=40, seed=9)
    fill_ridge(near, xs, ys, (22, 12, 44, 255))
    img = Image.alpha_composite(img, near)
    # a few warm lights of a village on the nearest ridge
    lights = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ld = ImageDraw.Draw(lights)
    rnd = random.Random(21)
    for _ in range(34):
        x = rnd.randint(40, W - 40)
        y = int(np.interp(x, xs, ys)) + rnd.randint(14, 70)
        ld.rectangle([x, y, x + 3, y + 3], fill=(255, 205, 130, rnd.randint(150, 240)))
    img = Image.alpha_composite(img, blur(lights, 3))
    img = Image.alpha_composite(img, lights)
    return img


def mist(y, color, strength):
    layer = np.zeros((H, W, 4), dtype="uint8")
    ys = np.arange(H)
    alpha = np.exp(-((ys - y) / 70.0) ** 2) * strength * 3.2
    layer[..., 0], layer[..., 1], layer[..., 2] = color
    layer[..., 3] = np.clip(alpha, 0, 255)[:, None]
    return blur(Image.fromarray(layer, "RGBA"), 10)


# --------------------------------------------------------------------------- foreground
def sakura(draw, cx, cy, r, rot, rnd):
    """One blossom: five notched petals, a paler heart and a few stamens."""
    pink = (255, rnd.randint(168, 196), rnd.randint(196, 220))
    for i in range(5):
        a = rot + i * 2 * math.pi / 5
        px, py = cx + math.cos(a) * r * 0.62, cy + math.sin(a) * r * 0.62
        pts = []
        for t in range(0, 360, 12):
            tt = math.radians(t)
            # an ellipse with a dip at its outer end gives the heart-like notch
            rx, ry = r * 0.62, r * 0.50
            notch = 1 - 0.20 * math.exp(-((math.cos(tt) - 1) ** 2) * 14) if False else 1
            x, y = rx * math.cos(tt), ry * math.sin(tt) * (1 - 0.0)
            # notch on the far tip
            if math.cos(tt) > 0.82:
                y *= 1 - 0.55 * ((math.cos(tt) - 0.82) / 0.18)
            ca, sa = math.cos(a), math.sin(a)
            pts.append((px + x * ca - y * sa, py + x * sa + y * ca))
        draw.polygon(pts, fill=pink + (255,))
    draw.ellipse([cx - r * 0.30, cy - r * 0.30, cx + r * 0.30, cy + r * 0.30], fill=(255, 226, 238, 255))
    for i in range(7):
        a = rot + i * 2 * math.pi / 7
        draw.ellipse([cx + math.cos(a) * r * 0.16 - 1.5, cy + math.sin(a) * r * 0.16 - 1.5,
                      cx + math.cos(a) * r * 0.16 + 1.5, cy + math.sin(a) * r * 0.16 + 1.5], fill=(214, 70, 120, 255))


def bezier(p0, p1, p2, p3, n=120):
    t = np.linspace(0, 1, n)[:, None]
    p0, p1, p2, p3 = map(np.array, (p0, p1, p2, p3))
    return (1 - t) ** 3 * p0 + 3 * (1 - t) ** 2 * t * p1 + 3 * (1 - t) * t ** 2 * p2 + t ** 3 * p3


def taper(draw, pts, r0, r1, color):
    n = len(pts)
    for i, (x, y) in enumerate(pts):
        r = lerp(r0, r1, i / (n - 1))
        draw.ellipse([x - r, y - r, x + r, y + r], fill=color)


def make_front():
    rnd = random.Random(33)
    S = 1  # draw at final size; edges are softened by a light blur
    dark = (20, 8, 30, 255)

    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))

    # --- torii gate at the lower left, cut by the screen edge
    tor = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    td = ImageDraw.Draw(tor)
    gate = (30, 12, 36, 255)
    px1, px2, top, bottom = 150, 430, 640, H + 20
    for x in (px1, px2):
        td.polygon([(x - 26, bottom), (x - 20, top + 60), (x + 20, top + 60), (x + 26, bottom)], fill=gate)
    td.rectangle([px1 - 14, top + 190, px2 + 14, top + 222], fill=gate)  # nuki
    td.polygon([(px1 - 96, top + 14), (px1 - 40, top + 52), (px2 + 40, top + 52), (px2 + 96, top + 14),
                (px2 + 80, top - 10), (px2 + 30, top + 18), (px1 - 30, top + 18), (px1 - 80, top - 10)], fill=gate)  # kasagi
    td.rectangle([px1 - 40, top + 52, px2 + 40, top + 82], fill=gate)  # shimaki
    td.rectangle([(px1 + px2) // 2 - 14, top + 82, (px1 + px2) // 2 + 14, top + 190], fill=gate)  # gakuzuka
    img = Image.alpha_composite(img, tor)

    # --- cherry branch from the top right corner
    branch = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    bd = ImageDraw.Draw(branch)
    main = bezier((W + 60, 40), (1780, 120), (1640, 150), (1370, 330), 160)
    taper(bd, main, 20, 5, dark)
    twigs = []
    for i in range(10, 150, 13):
        x, y = main[i]
        direction = rnd.choice([-1, 1])
        end = (x + rnd.randint(-120, 40), y + rnd.randint(50, 190) * (1 if direction > 0 else 0.6))
        ctrl = ((x + end[0]) / 2 + rnd.randint(-30, 30), (y + end[1]) / 2 + rnd.randint(-30, 30))
        tw = bezier((x, y), ctrl, ctrl, end, 40)
        taper(bd, tw, lerp(8, 3, i / 150), 1.6, dark)
        twigs.append(tw)
    img = Image.alpha_composite(img, branch)

    # blossoms on the main branch and at the twig tips
    blossoms = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    bl = ImageDraw.Draw(blossoms)
    spots = [(p[0], p[1]) for p in main[25::6]]
    for tw in twigs:
        spots += [(tw[k][0], tw[k][1]) for k in (20, 30, 39)]
    for (x, y) in spots:
        for _ in range(rnd.randint(1, 3)):
            sakura(bl, x + rnd.randint(-30, 30), y + rnd.randint(-26, 26), rnd.randint(15, 31), rnd.random() * 6.28, rnd)
    glow = blur(blossoms, 9)
    img = Image.alpha_composite(img, glow)
    img = Image.alpha_composite(img, blossoms)

    # out-of-focus blossoms in the foreground give depth
    bokeh = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    kd = ImageDraw.Draw(bokeh)
    for _ in range(6):
        x, y = rnd.randint(1560, W), rnd.randint(-10, 300)
        sakura(kd, x, y, rnd.randint(34, 58), rnd.random() * 6.28, rnd)
    img = Image.alpha_composite(img, blur(bokeh, 8))
    return img


# --------------------------------------------------------------------------- icons
SS = 4
SIZE = 128


def icon(draw_fn):
    big = Image.new("L", (SIZE * SS, SIZE * SS), 0)
    draw_fn(ImageDraw.Draw(big), SIZE * SS)
    mask = big.resize((SIZE, SIZE), Image.LANCZOS)
    out = Image.new("RGBA", (SIZE, SIZE), (255, 255, 255, 0))
    out.putalpha(mask)
    return out


def torii(d, s):
    u = s / 128
    d.polygon([(10 * u, 30 * u), (30 * u, 38 * u), (98 * u, 38 * u), (118 * u, 30 * u), (112 * u, 20 * u), (96 * u, 28 * u), (32 * u, 28 * u), (16 * u, 20 * u)], fill=255)
    d.rectangle([24 * u, 40 * u, 104 * u, 50 * u], fill=255)
    d.rectangle([34 * u, 56 * u, 94 * u, 66 * u], fill=255)
    d.rectangle([32 * u, 40 * u, 42 * u, 112 * u], fill=255)
    d.rectangle([86 * u, 40 * u, 96 * u, 112 * u], fill=255)
    d.rectangle([58 * u, 50 * u, 70 * u, 58 * u], fill=255)


def gamepad(d, s):
    u = s / 128
    d.rounded_rectangle([8 * u, 36 * u, 120 * u, 96 * u], radius=26 * u, fill=255)
    d.ellipse([6 * u, 62 * u, 40 * u, 110 * u], fill=255)
    d.ellipse([88 * u, 62 * u, 122 * u, 110 * u], fill=255)
    # d-pad and buttons are cut out
    d.rectangle([26 * u, 55 * u, 50 * u, 64 * u], fill=0)
    d.rectangle([33 * u, 48 * u, 43 * u, 71 * u], fill=0)
    d.ellipse([80 * u, 50 * u, 92 * u, 62 * u], fill=0)
    d.ellipse([94 * u, 60 * u, 106 * u, 72 * u], fill=0)


def blossom(d, s):
    u = s / 128
    cx = cy = 64 * u
    for i in range(5):
        a = -math.pi / 2 + i * 2 * math.pi / 5
        pts = []
        for t in range(0, 360, 10):
            tt = math.radians(t)
            x, y = 26 * u * math.cos(tt), 19 * u * math.sin(tt)
            if math.cos(tt) > 0.8:
                y *= 1 - 0.6 * ((math.cos(tt) - 0.8) / 0.2)
            px, py = cx + math.cos(a) * 30 * u, cy + math.sin(a) * 30 * u
            ca, sa = math.cos(a), math.sin(a)
            pts.append((px + x * ca - y * sa, py + x * sa + y * ca))
        d.polygon(pts, fill=255)
    d.ellipse([cx - 9 * u, cy - 9 * u, cx + 9 * u, cy + 9 * u], fill=0)


def download(d, s):
    u = s / 128
    d.rectangle([54 * u, 14 * u, 74 * u, 62 * u], fill=255)
    d.polygon([(30 * u, 58 * u), (98 * u, 58 * u), (64 * u, 96 * u)], fill=255)
    d.rounded_rectangle([18 * u, 100 * u, 110 * u, 114 * u], radius=6 * u, fill=255)


def gear(d, s):
    u = s / 128
    cx = cy = 64 * u
    for i in range(8):
        a = i * math.pi / 4
        c, sn = math.cos(a), math.sin(a)
        w, r0, r1 = 11 * u, 36 * u, 56 * u
        d.polygon([(cx + c * r0 - sn * w, cy + sn * r0 + c * w), (cx + c * r1 - sn * w * 0.8, cy + sn * r1 + c * w * 0.8),
                   (cx + c * r1 + sn * w * 0.8, cy + sn * r1 - c * w * 0.8), (cx + c * r0 + sn * w, cy + sn * r0 - c * w)], fill=255)
    d.ellipse([cx - 42 * u, cy - 42 * u, cx + 42 * u, cy + 42 * u], fill=255)
    d.ellipse([cx - 17 * u, cy - 17 * u, cx + 17 * u, cy + 17 * u], fill=0)


def main():
    for sub in ("images", "icons"):
        os.makedirs(os.path.join(OUT, sub), exist_ok=True)
    for name, fn in (("bg_sky", make_sky), ("bg_mountains", make_mountains), ("bg_front", make_front)):
        img = fn()
        path = os.path.join(OUT, "images", name + ".webp")
        img.save(path, "WEBP", quality=88, method=6)
        print(name, os.path.getsize(path) // 1024, "KB")
    for name, fn in (("home", torii), ("systems", gamepad), ("favorites", blossom), ("downloads", download), ("settings", gear)):
        path = os.path.join(OUT, "icons", name + ".png")
        icon(fn).save(path, optimize=True)
        print(name, os.path.getsize(path), "bytes")


if __name__ == "__main__":
    main()
